name: Deploy Angular to GitHub Pages

on:
  push:
    branches: ["master"]     # <- usas master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      # Compila (sin forzar outputPath) y deja base-href para Project Pages
      - name: Build Angular (production)
        run: npm run build -- --configuration production --base-href "/${REPO_NAME}/"

      # Detecta autom치ticamente d칩nde qued칩 index.html (Angular 15-18)
      - name: Locate publish directory
        id: locate
        shell: bash
        run: |
          OUT=$(node -e "const a=require('./angular.json'); const p=Object.keys(a.projects)[0]; console.log(a.projects[p].architect.build.options.outputPath)")
          # Posibles ubicaciones del index
          if [ -f \"$OUT/index.html\" ]; then
            PUBLISH_DIR=\"$OUT\"
          elif [ -f \"$OUT/browser/index.html\" ]; then
            PUBLISH_DIR=\"$OUT/browser\"
          else
            echo \"No se encontr칩 index.html en $OUT ni en $OUT/browser\"
            exit 1
          fi
          echo \"PUBLISH_DIR=$PUBLISH_DIR\" >> $GITHUB_ENV
          echo \"Publish dir: $PUBLISH_DIR\"

      # 404 para SPA routing
      - name: Add SPA 404.html
        run: cp "$PUBLISH_DIR/index.html" "$PUBLISH_DIR/404.html"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.PUBLISH_DIR }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
