name: Deploy Angular to GitHub Pages

on:
  push:
    branches: ["master"]          # usa "master" si tu repo es master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      # Compila en dist/ (forzamos output-path para no depender del angular.json)
      - name: Build Angular (production)
        run: |
          npm run build -- --configuration production --output-path dist --base-href "/${REPO_NAME}/"

      # Reescritura SPA: 404.html -> index.html
      - name: Add SPA 404.html
        run: cp dist/index.html dist/404.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact (dist)
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
