name: Deploy Angular to GitHub Pages

on:
  push:
    branches: ["master"]     # usas master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy_pages.outputs.page_url }}   # <- actualizado
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build Angular (prod)
        run: |
          npm run build -- --configuration production --base-href "/${REPO_NAME}/"

      - name: Locate publish directory (robusto)
        id: locate
        shell: bash
        run: |
          OUT=$(node -e "const fs=require('fs');const a=JSON.parse(fs.readFileSync('./angular.json','utf8'));
            const p=a.defaultProject || Object.keys(a.projects||{})[0];
            const proj=(a.projects||{})[p]||{};
            const b=(proj.architect&&proj.architect.build)||(proj.targets&&proj.targets.build)||{};
            const opt=(b.options||{});
            process.stdout.write(opt.outputPath||'');")

          if [ -z "$OUT" ]; then
            CANDIDATE=$(find dist -type f -name index.html -print -quit 2>/dev/null || true)
            if [ -n "$CANDIDATE" ]; then
              OUT="$(dirname "$CANDIDATE")"
            fi
          fi

          if [ -n "$OUT" ] && [ -f "$OUT/index.html" ]; then
            PUBLISH_DIR="$OUT"
          elif [ -n "$OUT" ] && [ -f "$OUT/browser/index.html" ]; then
            PUBLISH_DIR="$OUT/browser"
          else
            echo "No se encontró index.html en $OUT ni en $OUT/browser ni en dist/**"
            exit 1
          fi

          echo "PUBLISH_DIR=$PUBLISH_DIR" >> $GITHUB_ENV
          echo "Publish dir: $PUBLISH_DIR"

      - name: Add SPA 404.html
        run: cp "$PUBLISH_DIR/index.html" "$PUBLISH_DIR/404.html"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.PUBLISH_DIR }}

      - name: Deploy to GitHub Pages
        id: deploy_pages                     # <- renombrado (antes era "deployment")
        uses: actions/deploy-pages@v4
